# Generated by Django 5.2.5 on 2025-09-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={"verbose_name": "Redactor", "verbose_name_plural": "Redactors"},
        ),
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(default=0),
        ),
    ]
